# Generated by Django 5.1.3 on 2024-11-08 00:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="detailed_description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Descrição Detalhada"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="project",
            name="value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Valor"
            ),
        ),
        migrations.AlterModelTable(
            name="project",
            table=None,
        ),
    ]
