# Generated by Django 5.1.3 on 2024-11-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_detailed_description_project_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/", verbose_name="Foto"
            ),
        ),
    ]
