# Generated by Django 5.1.3 on 2024-11-12 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_photo"),
        ("tipo_projeto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tipo_projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tipo_projeto.tipoprojeto",
                verbose_name="Tipo de Projeto",
            ),
        ),
    ]
