# Generated by Django 5.1.3 on 2024-11-08 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="task",
            table=None,
        ),
    ]
